### ISSUE TITLE
contrast is too low for code keywords...

### ISSUE THREAD

**Issue by kylebakerio** [solidity-by-example/solidity-by-example.github.io#179]
dark mode doesn't fix this for me, it's just a CSS issue.

in Foundation.css, here:
```css
.hljs-code,
.hljs-number,
.hljs-literal,
.hljs-keyword,
.hljs-selector-tag {
  color: #099;
}
```

Changing`#099` to `#0758fc` increases the contrast from 3 (insufficient) to 4.74 (passing) according to devtools.

will dig in and see if I can do a quick pull request.

**Comment by kylebakerio** [comment]
checked. Looks like it's a lib imported in [src/components/Html.tsx](https://github.com/solidity-by-example/solidity-by-example.github.io/blob/43e4810610fda2f5ec1535392bb1a40c9dd49641/src/components/Html.tsx). I am not familiar enough with this code context to just throw in a quick fix for this to do a CSS override in this context, unfortunately, but I hope someone else can.

**Comment by kylebakerio** [comment]
For now I've downloaded the stylebot chrome extension and added in this rule:
```css
.hljs-code, .hljs-keyword, .hljs-literal, .hljs-number, .hljs-selector-tag {
    color: #0758fc;
}
```

works for now.

**Comment by kylebakerio** [comment]
I've made some improvements to the readability of the comments as well--currently, these are the override styles I'm applying:

```css
.hljs-code, .hljs-keyword, .hljs-literal, .hljs-number, .hljs-selector-tag {
    color: #0758fc;
}

pre {
  background: #f5f5f5;
}

.hljs-comment, .hljs-quote {
    color: #5f5f55;
}
```
